### ISSUE TITLE
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for check_point.

### ISSUE THREAD

**Issue by mehadi-trackrep** [huschen/kaggle_speech_recognition#2]
There is an error when pressing the last command "python predict.py --ckpt check_point".
The error is below:

  File "/home/mehadi/anaconda3/envs/Kaggle_SR/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for check_point.

**Comment by huschen** [comment]
check_point is a tensorflow checkpoint file. 
You will need to train the model to gain the checkpoint file in order to do prediction/evaluation.

**Comment by mehadi-trackrep** [comment]
I have already understood that. BTW, thanks!!
